version: '3.8'

    
include:
  - ./airflow/docker-compose.yml
  # - ./kafka/docker-compose.yml
  # - ./spark/docker-compose.yml


volumes:
  kafka-data:
  spark-data:

networks:
  spark_data-network:
    driver: bridge
  airflow_data-network:
    driver: bridge  



