spark:
    image: bitnami/spark:3.5.0
    container_name: spark
    hostname: spark
    ports:
      - 8080:8080
      - 8081:7077
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_UI_PORT=8080
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=NO
      - SPARK_USER=spark
    volumes:
      - ./spark/consume_from_kafka:/opt/bitnami/spark/consume_from_kafka
      - ./spark/requirements.txt:/opt/bitnami/spark/requirements.txt
      - spark-data:/opt/bitnami/spark/data
    networks:
       - spark_data-network