version: '3.8'

services:

  spark:
      build:
        context: .
        dockerfile: Dockerfile
        args:
          - SPARK_SYSTEM_PASSWORD=$SPARK_SYSTEM_PASSWORD
      container_name: spark
      hostname: spark
      ports:
        - $SPARK_HOST_UI_PORT:$SPARK_UI_PORT
        - 7077:7077
      env_file:
        - ./.env
        - ../kafka/.env
        - ../cassandra/.env
        - ../postgres/.env
      volumes:
        - ./data_processing:/opt/bitnami/spark/data_processing
        - ./config/entrypoint.sh:/opt/bitnami/scripts/spark/entrypoint.sh
        - spark-data:$SPARK_VOLUME_PATH
      networks:
        - spark_data-network
        - airflow_data-network