version: '3.8'

services:

  spark:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: spark
      hostname: spark
      ports:
        - $SPARK_HOST_UI_PORT:$SPARK_UI_PORT
      env_file:
        - ./.env
        - ../kafka/.env
        - ../cassandra/.env
      volumes:
        - ./data-processing:/opt/bitnami/spark/data-processing
        - ./requirements.txt:/opt/bitnami/spark/requirements.txt
        - spark-data:$SPARK_VOLUME_PATH
      networks:
        - spark_data-network