
\set POSTGRES_HISTORICAL_DATA_DB `echo "$POSTGRES_HISTORICAL_DATA_DB"`
\set POSTGRES_AIRFLOW_USER `echo "$POSTGRES_AIRFLOW_USER"`
\set POSTGRES_AIRFLOW_USER_PASSWORD `echo "$POSTGRES_AIRFLOW_USER_PASSWORD"`
\set POSTGRES_AIRLFOW_DB `echo "$POSTGRES_AIRFLOW_DB"`



-- Check if the historical database exists
SELECT 'CREATE DATABASE ' || :'POSTGRES_HISTORICAL_DATA_DB'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = :'POSTGRES_HISTORICAL_DATA_DB') \gexec

-- -- Check if the airflow user exists
SELECT 'CREATE USER ' || :'POSTGRES_AIRFLOW_USER' || 'WITH PASSWORD ' || :'POSTGRES_AIRFLOW_USER_PASSWORD' ||
       ' SUPERUSER CREATEROLE REPLICATION BYPASSRLS'
WHERE NOT EXISTS (SELECT FROM pg_roles WHERE rolname = :'POSTGRES_AIRFLOW_USER') \gexec

-- -- Check if the airflow database exists and grant priviliges   
SELECT 'CREATE DATABASE ' || :'POSTGRES_AIRLFOW_DB'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = :'POSTGRES_AIRLFOW_DB') \gexec
GRANT ALL PRIVILEGES ON DATABASE :POSTGRES_AIRLFOW_DB TO :POSTGRES_AIRFLOW_USER;
