version: '3.8'
services:
  postgres:
    image: postgres:9.6
    container_name: postgres
    hostname: postgres
    ports:
          - $POSTGRES_HOST_PORT:$POSTGRES_PORT
    environment:
        - POSTGRES_DB=$POSTGRES_DB
        - POSTGRES_USER=$POSTGRES_USER
        - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    networks:
      - airflow_data-network

  airflow:
    build:
        context: .
        dockerfile: Dockerfile
        args:
          - SPARK_SYSTEM_PASSWORD=$SPARK_SYSTEM_PASSWORD
    container_name: airflow
    hostname: airflow
    depends_on:
      - postgres
    ports:
      - $AIRFLOW_HOST_PORT:$AIRFLOW_PORT
    env_file:
      -  ./.env
      - ../kafka/.env
      - ../spark/.env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./produce_to_kafka:/opt/airflow/produce_to_kafka
      - ./config/airflow.cfg:/opt/airflow/airflow.cfg
      - ./config/entrypoint.sh:/entrypoint
    networks:
      - airflow_data-network

