version: '3.8'
services:
  airflow:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: airflow
    hostname: airflow
    depends_on:
      - postgres
    ports:
      - $AIRFLOW_HOST_PORT:$AIRFLOW_PORT
    env_file:
      -  ./.env
      - ../postgres/.env
      - ../kafka/.env
      - ../spark/.env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./produce_to_kafka:/opt/airflow/produce_to_kafka
      - ./config/airflow.cfg:/opt/airflow/airflow.cfg
      - ./config/entrypoint.sh:/entrypoint
    networks:
      - airflow_data-network

