version: '3.8'
services:
  postgres:
    image: postgres:9.6
    container_name: postgres
    hostname: postgres
    ports:
          - $POSTGRES_HOST_PORT:$POSTGRES_PORT
    environment:
        - POSTGRES_DB=$POSTGRES_DB
        - POSTGRES_USER=$POSTGRES_USER
        - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    networks:
      - airflow_data-network

  airflow:
    image: apache/airflow:2.6.0-python3.9
    container_name: airflow
    hostname: airflow
    depends_on:
      - postgres
    ports:
      - $AIRFLOW_HOST_PORT:$AIRFLOW_PORT
    env_file:
      -  ./.env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./config/airflow.cfg:/opt/airflow/airflow.cfg
      - ./config/entrypoint.sh:/entrypoint
      - ./requirements.txt:/opt/airflow/requirements.txt
    networks:
      - airflow_data-network
         

