version: '3.8'

services:

  kafka1:
      image: bitnami/kafka:3.5.0
      container_name: kafka1
      hostname: kafka1
      ports:
        - "9092:9092"
        - "9093:9093"
      volumes:
        - ./kafka/config/entrypoint.sh:/entrypoint.sh
        - ./kafka/scripts/:/scripts
        - kafka-data:/var/lib/kafka/data
      networks:
        - airflow_data-network
        - spark_data-network