version: '3.8'
services:
  postgres:
    image: postgres:9.6
    container_name: postgres
    hostname: postgres
    ports:
        - $POSTGRES_HOST_PORT:$POSTGRES_PORT
    env_file:
        - ./.env      
    environment:
        - POSTGRES_USER=$POSTGRES_USER
        - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
        - ./scripts:/docker-entrypoint-initdb.d/
        - postgres-data:/var/lib/postgresql/data
        - ./config/entrypoint.sh:/entrypoint.sh
    entrypoint:
       /entrypoint.sh
    networks:
      - airflow_data-network
      - spark_data-network
      - dashboard-network